name = "NewGokarna"
description = "NewGokarna is an opinionated theme with a focus on minimalism and simplicity"

license = "GNU GPLv3"
licenselink = "https://github.com/illia-danko/neo-gokarna/blob/main/LICENSE"

homepage = "https://github.com/illia-danko/neo-gokarna"
demosite = "https://illia.danko.ws"

tags = ["blog", "minimal", "dark", "light", "responsive", "personal", "portfolio"]

features = ["Blog", "Responsive", "Minimal", "Clean", "Simple", "SEO", "Bootstrap", "Fast", "Dark", "Light"]

authors = [
  {name = "Yash Mehrotra", homepage = "https://yashmehrotra.com"},
  {name = "Avijit Gupta", homepage = "https://526avijitgupta.github.io"},
  {name = "Illia Danko", homepage = "https://illia.danko.ws"},
]

min_version = "0.81.0"
